---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint .
driver:
  name: vagrant
  provider: 
    name: virtualbox
platforms:
  - name: debian10-node
    box: debian/buster64
    memory: 2048
    cpu: 1
provisioner:
  name: ansible
verifier:
  name: ansible
