---
- name: Converge
  hosts: all
  tasks:
    - name: install apt required packages
      apt:
        name:
          - gnupg2
        update_cache: yes
      become: true

    - name: "Include ansible_role_kubectl"
      include_role:
        name: "ansible_role_kubectl"
